name: ci
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Run Linting
        run: yarn lint

      - name: Run Typecheck
        run: yarn typecheck
